### ISSUE TITLE
Update Job Opportunities

### ISSUE THREAD

**Issue by mollyxu** [calixo888/lt-site#2]
For the software engineer and product management job opportunities on the website, when the apply button is clicked, it leads to the "contact us!" section. 
![Screen Shot 2020-06-20 at 11 30 33 AM](https://user-images.githubusercontent.com/64995721/85208985-751a3f80-b2e9-11ea-9b78-072d9e1f580f.png)

If this is because there are no longer openings, then they should be taken off of the page.

**Comment by jinhao27** [comment]
people applying usually would contact. Closing for now

**Comment by jinhao27** [comment]
People applying usually will contact directly. Can be closed for now.
